/**
 * Calls Gemini API to rewrite text into workplace-safe language.
 * @param message User-provided raw text that needs corporatifying.
 * @param tone Selected output tone shown in the dashboard dropdown.
 * @returns Rewritten professional response generated by Gemini.
 */
export function corporatifyMessage(
  message: string,
  tone: 'Polite' | 'Very Polite' | 'Passive Aggressive',
): Promise<string>;
